# Generated by Django 4.2.11 on 2024-03-11 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("request", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="review",
            options={"default_related_name": "review"},
        ),
        migrations.AlterField(
            model_name="registrant",
            name="type",
            field=models.CharField(
                choices=[
                    ("Central government department or agency", "Central Government"),
                    (
                        "Non-departmental body - also known as an arm's length body",
                        "Ndpb",
                    ),
                    ("Fire Service", "Fire Service"),
                    (
                        "County, borough, metropolitan or district council",
                        "Local Authority",
                    ),
                    ("Parish, town or community council", "Parish Council"),
                    ("Neighbourhood or village council", "Village Council"),
                    ("Combined or unitary authority", "Combined Authority"),
                    ("Police and Crime Commissioner", "Pcc"),
                    ("Joint Authority", "Joint Authority"),
                    ("Joint Committee", "Joint Committee"),
                    ("Representing public sector bodies", "Representative"),
                ],
                max_length=100,
            ),
        ),
    ]
