# Generated by Django 4.2.11 on 2024-04-24 14:21

from django.db import migrations, models
import request_a_govuk_domain.request.models.storage_util


class Migration(migrations.Migration):
    dependencies = [
        ("request", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="written_permission_evidence",
            field=models.FileField(
                storage=request_a_govuk_domain.request.models.storage_util.select_storage,
                upload_to="",
            ),
        ),
        migrations.AlterField(
            model_name="centralgovernmentattributes",
            name="ministerial_request_evidence",
            field=models.FileField(
                blank=True,
                null=True,
                storage=request_a_govuk_domain.request.models.storage_util.select_storage,
                upload_to="",
            ),
        ),
        migrations.AlterField(
            model_name="centralgovernmentattributes",
            name="policy_exemption_evidence",
            field=models.FileField(
                blank=True,
                null=True,
                storage=request_a_govuk_domain.request.models.storage_util.select_storage,
                upload_to="",
            ),
        ),
    ]
