# Generated by Django 4.2.9 on 2024-02-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("request", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistrationData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("registrant_full_name", models.CharField(max_length=100)),
                ("registrant_email_address", models.EmailField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name="UserData",
        ),
    ]
