# Generated by Django 4.2.11 on 2024-03-13 12:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("request", "0002_alter_review_options_alter_registrant_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="registrant",
            name="organisation_ptr",
        ),
        migrations.RemoveField(
            model_name="registrar",
            name="organisation_ptr",
        ),
        migrations.AddField(
            model_name="registrant",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="registrant",
            name="name",
            field=models.CharField(default="unknown name"),
        ),
        migrations.AddField(
            model_name="registrar",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="registrar",
            name="name",
            field=models.CharField(default="unknown name"),
        ),
        migrations.DeleteModel(
            name="Organisation",
        ),
    ]
