# Generated by Django 4.2.13 on 2024-05-28 09:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("request", "0003_historicalreview_registry_details_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="historicalreview",
            name="domain_name_availability_notes",
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name="historicalreview",
            name="domain_name_rules_notes",
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name="historicalreview",
            name="policy_exemption_notes",
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name="historicalreview",
            name="registrant_org_notes",
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name="historicalreview",
            name="registrant_permission_notes",
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name="historicalreview",
            name="registrant_person_notes",
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name="historicalreview",
            name="registrant_senior_support_notes",
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name="historicalreview",
            name="registrar_details_notes",
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name="review",
            name="domain_name_availability_notes",
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name="review",
            name="domain_name_rules_notes",
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name="review",
            name="policy_exemption_notes",
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name="review",
            name="registrant_org_notes",
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name="review",
            name="registrant_permission_notes",
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name="review",
            name="registrant_person_notes",
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name="review",
            name="registrant_senior_support_notes",
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name="review",
            name="registrar_details_notes",
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
