# Generated by Django 4.2.13 on 2024-05-29 11:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("request", "0004_application_last_updated_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalreview",
            name="registry_details_notes",
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name="review",
            name="registry_details_notes",
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
