# Generated by Django 4.2.13 on 2024-07-19 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("request", "0010_alter_application_ministerial_request_evidence_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("on_hold_days", models.IntegerField(default=5)),
                ("to_close_days", models.IntegerField(default=60)),
            ],
        ),
        migrations.AlterField(
            model_name="application",
            name="status",
            field=models.CharField(
                choices=[
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("in_progress", "In Progress"),
                    ("ready_2i", "Ready for 2i"),
                    ("more_information", "More Information"),
                    ("new", "New"),
                    ("on_hold", "On-hold"),
                    ("failed_confirmation_email", "Failed Confirmation Email"),
                    ("failed_decision_email", "Failed Decision Email"),
                ],
                default="new",
                max_length=25,
            ),
        ),
    ]
