# Generated by Django 4.2.13 on 2024-08-06 13:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("request", "0013_merge_20240805_1025"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="status",
            field=models.CharField(
                choices=[
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("in_progress", "In Progress"),
                    ("ready_2i", "Ready for 2i"),
                    ("more_information", "More Information"),
                    ("with_nac", "Currently with NAC"),
                    ("new", "New"),
                    ("duplicate_application", "Duplicate application"),
                    ("failed_confirmation_email", "Failed Confirmation Email"),
                    ("failed_decision_email", "Failed Decision Email"),
                ],
                default="new",
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="historicalreview",
            name="policy_exemption",
            field=models.CharField(
                choices=[
                    ("approve", "Strong evidence exists - approve"),
                    ("holding", "Need more info - on hold, awaiting response"),
                    ("reject", "Insufficient evidence exists - reject"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="historicalreview",
            name="policy_exemption_notes",
            field=models.TextField(
                max_length=5000,
                validators=[django.core.validators.MinLengthValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="historicalreview",
            name="registrant_senior_support",
            field=models.CharField(
                choices=[
                    ("approve", "Strong evidence exists - approve"),
                    ("holding", "Need more info - on hold, awaiting response"),
                    ("reject", "Insufficient evidence exists - reject"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="historicalreview",
            name="registrant_senior_support_notes",
            field=models.TextField(
                max_length=5000,
                validators=[django.core.validators.MinLengthValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="policy_exemption",
            field=models.CharField(
                choices=[
                    ("approve", "Strong evidence exists - approve"),
                    ("holding", "Need more info - on hold, awaiting response"),
                    ("reject", "Insufficient evidence exists - reject"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="policy_exemption_notes",
            field=models.TextField(
                max_length=5000,
                validators=[django.core.validators.MinLengthValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="registrant_senior_support",
            field=models.CharField(
                choices=[
                    ("approve", "Strong evidence exists - approve"),
                    ("holding", "Need more info - on hold, awaiting response"),
                    ("reject", "Insufficient evidence exists - reject"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="registrant_senior_support_notes",
            field=models.TextField(
                max_length=5000,
                validators=[django.core.validators.MinLengthValidator(1)],
            ),
        ),
    ]
