# Generated by Django 4.2.13 on 2025-04-24 20:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("request", "0023_historicalregistrar_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="sub_status",
            field=models.CharField(
                choices=[
                    ("approved_no_delay", "Approved (with no delay)"),
                    (
                        "approved_delayed_registrant_id",
                        "Approved, but delayed by Registrant ID/Organization verification",
                    ),
                    (
                        "approved_delayed_registry_published",
                        "Approved, but delayed by Registry published details",
                    ),
                    (
                        "approved_delayed_evidence",
                        "Approved, but delayed by Issues with evidence",
                    ),
                    ("approved_delayed_other", "Approved, but delayed by Other types"),
                    ("approved_with_nac", "Approved with NAC"),
                    ("rejected_no_delay", "Rejected (with no delay)"),
                    (
                        "rejected_delayed_registrant_id",
                        "Rejected, but delayed by Registrant ID/Organization verification",
                    ),
                    (
                        "rejected_delayed_registry_published",
                        "Rejected, but delayed by Registry published details",
                    ),
                    (
                        "rejected_delayed_evidence",
                        "Rejected, but delayed by Issues with evidence",
                    ),
                    ("rejected_delayed_other", "Rejected, but delayed by Other types"),
                    ("rejected_with_nac", "Rejected with NAC"),
                ],
                default="approved_no_delay",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="historicalapplication",
            name="sub_status",
            field=models.CharField(
                choices=[
                    ("approved_no_delay", "Approved (with no delay)"),
                    (
                        "approved_delayed_registrant_id",
                        "Approved, but delayed by Registrant ID/Organization verification",
                    ),
                    (
                        "approved_delayed_registry_published",
                        "Approved, but delayed by Registry published details",
                    ),
                    (
                        "approved_delayed_evidence",
                        "Approved, but delayed by Issues with evidence",
                    ),
                    ("approved_delayed_other", "Approved, but delayed by Other types"),
                    ("approved_with_nac", "Approved with NAC"),
                    ("rejected_no_delay", "Rejected (with no delay)"),
                    (
                        "rejected_delayed_registrant_id",
                        "Rejected, but delayed by Registrant ID/Organization verification",
                    ),
                    (
                        "rejected_delayed_registry_published",
                        "Rejected, but delayed by Registry published details",
                    ),
                    (
                        "rejected_delayed_evidence",
                        "Rejected, but delayed by Issues with evidence",
                    ),
                    ("rejected_delayed_other", "Rejected, but delayed by Other types"),
                    ("rejected_with_nac", "Rejected with NAC"),
                ],
                default="approved_no_delay",
                max_length=50,
            ),
        ),
    ]
